export const enum NETWORK_ERROR_ENUM {
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    PERMISSION = 403,
    NOT_FOUND = 404,
    SERVER_ERROR = 500,
    SERVICE_UNAVAILABLE = 503,
    GATEWAY_TIMEOUT = 504
}

export const enum NETWORK_SUCCESS_ENUM {
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    PERMISSION = 403,
    NOT_FOUND = 404,
    SERVER_ERROR = 500,
    SERVICE_UNAVAILABLE = 503,
    GATEWAY_TIMEOUT = 504
}
