name: Deploy dashboard into Github Pages  

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses:  actions/checkout@v3

      - name: Setup Node
        uses:  actions/checkout@v3
        with:
          node-version: 19
          cache: 'npm'

      - name: Install libary and plugin in project
        uses: npm install

      - name: Build project by vite and npm
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist